CREATE SCHEMA IF NOT EXISTS musics;

CREATE TABLE IF NOT EXISTS musics.composers (
    ID INT NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BIRTH_YEAR INT NOT NULL
);

CREATE TABLE IF NOT EXISTS musics.musicals (
    ID INT NOT NULL PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    RELEASE_YEAR INT NOT NULL,
    COMPOSER_ID INT NOT NULL REFERENCES musics.composers(ID)
);

CREATE SEQUENCE IF NOT EXISTS musics.composer_seq
    INCREMENT 1
    START 1000;

CREATE SEQUENCE IF NOT EXISTS musics.musical_seq
    INCREMENT 1
    START 1000;
