CREATE TABLE cars.admin_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_in_cents BIGINT NOT NULL DEFAULT 0
);

INSERT INTO cars.admin_account (balance_in_cents) VALUES (0);